# Generated by Django 2.0.1 on 2018-01-29 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentchannel',
            name='signature',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
