# Generated by Django 2.0.1 on 2018-01-29 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180129_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentchannel',
            name='used_amount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
