# Generated by Django 2.0.1 on 2018-02-12 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20180208_0906'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentchannel',
            name='is_settled',
            field=models.BooleanField(default=False),
        ),
    ]
