# Generated by Django 2.0.2 on 2018-02-16 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_paymentchannel_is_settled'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentchannel',
            name='is_timed_out',
            field=models.BooleanField(default=False),
        ),
    ]
