# Generated by Django 2.0.2 on 2018-02-16 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_paymentchannel_is_timed_out'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentchannel',
            name='is_failed',
            field=models.BooleanField(default=False),
        ),
    ]
